<a href="https://colab.research.google.com/github/emanespitia/restaurantSystem-/blob/main/Linear_Algebra_Project_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Generate 3 random numbers between 0 and 1
x0 = (1,2,4)

print(f"Initial PageRanks: {x0}")

Initial PageRanks: (1, 2, 4)


In [ ]:
import numpy as np

# Define matrix A
A = np.array([[0, 1, 0.5],
              [0.5, 0, 0.5],
              [0.5, 0, 0]])

# Assuming x0 is already defined from the previous step (random PageRanks)
# If not, uncomment the following line to generate it:
# x0 = np.random.rand(3)

# Calculate Ax_1
Ax_1 = np.dot(A, x0)

print(f"Ax_1: {Ax_1}")

Ax_1: [4.  2.5 0.5]


In [ ]:
import numpy as np

# Define matrix A (assuming it's already defined from previous steps)
# A = np.array([[0, 1, 0.5],
#               [0.5, 0, 0.5],
#               [0.5, 0, 0]])

# Assuming Ax_0 is already defined from previous steps
# If not, you'll need to calculate it using:
# Ax_0 = np.dot(A, x0)  (where x0 is the initial PageRanks vector)

# Calculate A^15 and A^16
A_15 = np.linalg.matrix_power(A, 15)
A_16 = np.linalg.matrix_power(A, 16)

# Compare A^15 and A^16
difference = np.linalg.norm(A_15 - A_16)  # Calculate the difference

print(f"A^15:\n{A_15}\n")
print(f"A^16:\n{A_16}\n")
print(f"Difference (norm): {difference}")

A^15:
[[0.4442749  0.44476318 0.44430542]
 [0.33334351 0.33331299 0.33334351]
 [0.22238159 0.22192383 0.22235107]]

A^16:
[[0.4445343  0.4442749  0.44451904]
 [0.33332825 0.33334351 0.33332825]
 [0.22213745 0.22238159 0.22215271]]

Difference (norm): 0.0008131660519088274
