<a href="https://colab.research.google.com/github/emanespitia/restaurantSystem-/blob/main/Linear_Algebra_Project_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Generate 3 random numbers between 0 and 1
x0 = (1,2,4)

print(f"Initial PageRanks: {x0}")

Initial PageRanks: (1, 2, 4)


In [ ]:
import numpy as np

# Define matrix A
A = np.array([[0, 1, 0.5],
              [0.5, 0, 0.5],
              [0.5, 0, 0]])

# Assuming x0 is already defined from the previous step (random PageRanks)
# If not, uncomment the following line to generate it:
# x0 = np.random.rand(3)

# Calculate Ax_1
Ax_1 = np.dot(A, x0)

print(f"Ax_1: {Ax_1}")

Ax_1: [4.  2.5 0.5]


In [ ]:
import numpy as np

# Define matrix A (assuming it's already defined from previous steps)
# A = np.array([[0, 1, 0.5],
#               [0.5, 0, 0.5],
#               [0.5, 0, 0]])

# Assuming Ax_0 is already defined from previous steps
# If not, you'll need to calculate it using:
# Ax_0 = np.dot(A, x0)  (where x0 is the initial PageRanks vector)

# Calculate A^15 and A^16
A_15 = np.linalg.matrix_power(A, 15)
A_16 = np.linalg.matrix_power(A, 16)

# Compare A^15 and A^16
difference = np.linalg.norm(A_15 - A_16)  # Calculate the difference

print(f"A^15:\n{A_15}\n")
print(f"A^16:\n{A_16}\n")
print(f"Difference (norm): {difference}")

A^15:
[[0.4442749  0.44476318 0.44430542]
 [0.33334351 0.33331299 0.33334351]
 [0.22238159 0.22192383 0.22235107]]

A^16:
[[0.4445343  0.4442749  0.44451904]
 [0.33332825 0.33334351 0.33332825]
 [0.22213745 0.22238159 0.22215271]]

Difference (norm): 0.0008131660519088274


In [7]:
import sympy as sp
import numpy as np

# Define matrix A
A = np.array([[0, 1, 0.5],
              [0.5, 0, 0.5],
              [0.5, 0, 0]])

# Define x0
x0 = (1, 2, 4)

# Calculate Ax_1
Ax_1 = np.dot(A, x0)

# Define the augmented matrix
augmented_matrix = sp.Matrix([[0, 1, 0.5, Ax_1[0]],
                               [0.5, 0, 0.5, Ax_1[1]],
                               [0.5, 0, 0, Ax_1[2]]])

# Get the rref
rref_matrix, pivot_columns = augmented_matrix.rref()

print(rref_matrix)

Matrix([[1, 0, 0, 1.00000000000000], [0, 1, 0, 2.00000000000000], [0, 0, 1, 4.00000000000000]])


In [8]:
import numpy as np

# Define matrix A
A = np.array([[0, 1, 0.5],
              [0.5, 0, 0.5],
              [0.5, 0, 0]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Print the results
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

# Access the eigenvector corresponding to the first eigenvalue (as an example)
first_eigenvector = eigenvectors[:, 0]
print("\nFirst Eigenvector:", first_eigenvector)

Eigenvalues: [ 1.  -0.5 -0.5]
Eigenvectors:
 [[-7.42781353e-01 -7.07106778e-01  7.07106784e-01]
 [-5.57086015e-01 -5.56097898e-09 -5.56097881e-09]
 [-3.71390676e-01  7.07106784e-01 -7.07106778e-01]]

First Eigenvector: [-0.74278135 -0.55708601 -0.37139068]


In [9]:
import numpy as np

# Define matrix A
A = np.array([[0, 1, 0.5],
              [0.5, 0, 0.5],
              [0.5, 0, 0]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Find the eigenvector corresponding to the largest eigenvalue (dominant eigenvector)
dominant_eigenvector_index = np.argmax(eigenvalues)
dominant_eigenvector = eigenvectors[:, dominant_eigenvector_index]

# Normalize the eigenvector to represent probabilities
dominant_eigenvector = dominant_eigenvector / np.sum(dominant_eigenvector)

# Get the ranking based on the eigenvector components
ranking = np.argsort(dominant_eigenvector)[::-1]  # Sort in descending order

# Print the ranking
print("PageRank Order:")
for i in ranking:
    print(f"Page {i + 1}: PageRank = {dominant_eigenvector[i]}")

PageRank Order:
Page 1: PageRank = 0.4444444444444444
Page 2: PageRank = 0.3333333333333333
Page 3: PageRank = 0.22222222222222227
